# Site settings

title: "Savithru Lokanath"
description: ""

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

resume_avatar:                  "true"
resume_name:                    "Savithru Lokanath"
resume_title:                   "Bits & bytes"

resume_header_contact_info:     "San Francisco Bay Area, CA • savithru@colorado.edu"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am an <em>engineer</em> solving technology problems at scale. When not writing code, I'm probably wearing my <em>janitor</em> hat & plumbing networks.</p>I'd like to introduce to my new AI assistant powered by ChatGPT, <em><a href=https://www.shabdkosh.com/dictionary/kannada-english/kaalpanika/kaalpanika-meaning-in-english target=_blank>Kalpanika</a></em>. She's located at the bottom right of this screen & she can tell more about me!"

resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
resume_section_links:           true
resume_section_top:             true
patents:                        true

resume_social_links:
  resume_linkedin_url:          "https://www.linkedin.com/in/savvythrough"
  resume_medium_url:            "https://medium.com/@savvythrough"
  resume_github_url:            "https://github.com/savithruml"
resume_print_social_links:      true

resume_theme:                   default
